<h1 data-toc="exceptions" id="exceptions.md">Exceptions</h1>
<section class="chapter"><h2 id="exception-classes" data-toc="exceptions#exception-classes">Exception classes</h2>
<p id="b5063a0e">All exception classes in Kotlin inherit the <code class="code ">Throwable</code> class. Every exception has a message, a stack trace, and an optional cause.</p>
<p id="e5302e9f">To throw an exception object, use the <code class="code ">throw</code> expression:</p>
<pre class="code" data-language="kotlin">fun main() {
//sampleStart
    throw Exception("Hi There!")
//sampleEnd
}
</pre>
<p id="2702a402">To catch an exception, use the <code class="code ">try</code>...<code class="code ">catch</code> expression:</p>
<pre class="code" data-language="kotlin">try {
    // some code
} catch (e: SomeException) {
    // handler
} finally {
    // optional finally block
}
</pre>
<p id="64c012c1">There may be zero or more <code class="code ">catch</code> blocks, and the <code class="code ">finally</code> block may be omitted. However, at least one <code class="code ">catch</code> or <code class="code ">finally</code> block is required.</p>
<section class="chapter"><h3 id="try-is-an-expression" data-toc="exceptions#try-is-an-expression">Try is an expression</h3>
<p id="34550214"><code class="code ">try</code> is an expression, which means it can have a return value:</p>
<pre class="code" data-language="kotlin">val a: Int? = try { input.toInt() } catch (e: NumberFormatException) { null }
</pre>
<p id="57991b01">The returned value of a <code class="code ">try</code> expression is either the last expression in the <code class="code ">try</code> block or the last expression in the <code class="code ">catch</code> block (or blocks). The contents of the <code class="code ">finally</code> block don't affect the result of the expression.</p></section></section><section class="chapter"><h2 id="checked-exceptions" data-toc="exceptions#checked-exceptions">Checked exceptions</h2>
<p id="b498dfb5">Kotlin does not have checked exceptions. There are many reasons for this, but we will provide a simple example that illustrates why it is the case.</p>
<p id="4084a97e">The following is an example interface from the JDK implemented by the <code class="code ">StringBuilder</code> class:</p>
<pre class="code" data-language="java">Appendable append(CharSequence csq) throws IOException;
</pre>
<p id="6d3243d2">This signature says that every time I append a string to something (a <code class="code ">StringBuilder</code>, some kind of a log, a console, etc.), I have to catch the <code class="code ">IOExceptions</code>. Why? Because the implementation might be performing IO operations (<code class="code ">Writer</code> also implements <code class="code ">Appendable</code>). The result is code like this all over the place:</p>
<pre class="code" data-language="kotlin">try {
    log.append(message)
} catch (IOException e) {
    // Must be safe
}
</pre>
<p id="680de5ba">And that’s not good. Just take a look at <a href="https://www.oracle.com/technetwork/java/effectivejava-136174.html" id="16518a95" data-external="true" rel="noopener noreferrer">Effective Java, 3rd Edition</a>, Item 77: <em id="532e30fe" class="">Don't ignore exceptions</em>.</p>
<p id="48d9878b">Bruce Eckel says this about checked exceptions:</p>
<aside data-type="tip" class="prompt" data-title="" id="1a58493"><p id="ef0c9599">Examination of small programs leads to the conclusion that requiring exception specifications could both enhance developer productivity and enhance code quality, but experience with large software projects suggests a different result – decreased productivity and little or no increase in code quality.</p></aside><p id="d27a4d03">And here are some additional thoughts on the matter:</p>
<ul class="list _ul" id="c8c54a8b">
<li class="list__item" id="853d018c"><p><a href="https://radio-weblogs.com/0122027/stories/2003/04/01/JavasCheckedExceptionsWereAMistake.html" id="83ef85f8" data-external="true" rel="noopener noreferrer">Java's checked exceptions were a mistake</a> (Rod Waldhoff)</p></li>
<li class="list__item" id="8b50bbc0"><p><a href="https://www.artima.com/intv/handcuffs.html" id="d5847bd1" data-external="true" rel="noopener noreferrer">The Trouble with Checked Exceptions</a> (Anders Hejlsberg)</p></li>
</ul>
<p id="40553f8e">If you want to alert callers about possible exceptions when calling Kotlin code from Java, Swift, or Objective-C, you can use the <code class="code ">@Throws</code> annotation. Read more about using this annotation <a href="java-to-kotlin-interop#checked-exceptions" id="a7140ae">for Java</a> and <a href="native-objc-interop#errors-and-exceptions" id="c29df170">for Swift and Objective-C</a>.</p></section><section class="chapter"><h2 id="the-nothing-type" data-toc="exceptions#the-nothing-type">The Nothing type</h2>
<p id="c9eecfbc"><code class="code ">throw</code> is an expression in Kotlin, so you can use it, for example, as part of an Elvis expression:</p>
<pre class="code" data-language="kotlin">val s = person.name ?: throw IllegalArgumentException("Name required")
</pre>
<p id="5c165c45">The <code class="code ">throw</code> expression has the type <code class="code ">Nothing</code>. This type has no values and is used to mark code locations that can never be reached. In your own code, you can use <code class="code ">Nothing</code> to mark a function that never returns:</p>
<pre class="code" data-language="kotlin">fun fail(message: String): Nothing {
    throw IllegalArgumentException(message)
}
</pre>
<p id="d2d4391f">When you call this function, the compiler will know that the execution doesn't continue beyond the call:</p>
<pre class="code" data-language="kotlin">val s = person.name ?: fail("Name required")
println(s)     // 's' is known to be initialized at this point
</pre>
<p id="cc22f181">You may also encounter this type when dealing with type inference. The nullable variant of this type, <code class="code ">Nothing?</code>, has exactly one possible value, which is <code class="code ">null</code>. If you use <code class="code ">null</code> to initialize a value of an inferred type and there's no other information that can be used to determine a more specific type, the compiler will infer the <code class="code ">Nothing?</code> type:</p>
<pre class="code" data-language="kotlin">val x = null           // 'x' has type `Nothing?`
val l = listOf(null)   // 'l' has type `List&lt;Nothing?&gt;
</pre></section><section class="chapter"><h2 id="java-interoperability" data-toc="exceptions#java-interoperability">Java interoperability</h2>
<p id="99b23d0c">Please see the section on exceptions in the <a href="java-interop" id="de33a611">Java interoperability page</a> for information about Java interoperability.</p></section><div class="last-modified"> Last modified: 08 August 2022</div>

<div class="navigation-links _bottom"> <a class="navigation-links__prev" href="returns">Returns and jumps</a> <a class="navigation-links__next" href="packages">Packages and imports</a> </div><div class="_attribution">
  <p class="_attribution-p">
    <a href="https://kotlinlang.org/docs/exceptions.html" class="_attribution-link" target="_blank">https://kotlinlang.org/docs/exceptions.html</a>
  </p>
</div>
