<h1 id="recover">recover</h1>
<div class="api-docs-breadcrumbs">
<a href="../../../../../index">kotlin-stdlib</a> / <a href="index">kotlin</a> / <a href="recover">recover</a>
</div> <div class="node-page-main" data-kotlin-version="1.3, 1.3, 1.3, 1.3" data-platform="Common, JVM, JS, Native">
<div data-kotlin-version="1.3, 1.3, 1.3, 1.3" data-platform="Common, JVM, JS, Native">
<b>Platform and version requirements:</b> JVM (1.3), JS (1.3), Native (1.3) </div>
<div data-kotlin-version="1.3, 1.3, 1.3, 1.3" data-platform="Common, JVM, JS, Native">
 <pre class="signature" data-language="kotlin">inline fun &lt;R, T : R&gt; Result&lt;T&gt;.recover(
    transform: (exception: Throwable) -&gt; R
): Result&lt;R&gt;</pre> </div>
<div data-kotlin-version="1.3, 1.3, 1.3, 1.3" data-platform="Common, JVM, JS, Native"> <p>Returns the encapsulated result of the given <a href="recover#kotlin%24recover(kotlin.Result((kotlin.recover.T)),%20kotlin.Function1((kotlin.Throwable,%20kotlin.recover.R)))/transform">transform</a> function applied to the encapsulated <a href="-throwable/index#kotlin.Throwable">Throwable</a> exception if this instance represents <a href="-result/is-failure">failure</a> or the original encapsulated value if it is <a href="-result/is-success">success</a>.</p> <p>Note, that this function rethrows any <a href="-throwable/index#kotlin.Throwable">Throwable</a> exception thrown by <a href="recover#kotlin%24recover(kotlin.Result((kotlin.recover.T)),%20kotlin.Function1((kotlin.Throwable,%20kotlin.recover.R)))/transform">transform</a> function. See <a href="recover-catching">recoverCatching</a> for an alternative that encapsulates exceptions.</p> </div>
</div><div class="_attribution">
  <p class="_attribution-p">
    <a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/recover.html" class="_attribution-link" target="_blank">https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/recover.html</a>
  </p>
</div>
