<h1 id="pandas-errors-unsupportedfunctioncall">pandas.errors.UnsupportedFunctionCall</h1> <dl class="exception"> <dt id="pandas.errors.UnsupportedFunctionCall">
<code>exception pandas.errors.UnsupportedFunctionCall</code> <a class="reference external" href="http://github.com/pandas-dev/pandas/blob/v0.25.0/pandas/errors/__init__.py#L16-L21"><span class="viewcode-link">[source]</span></a>
</dt> <dd>
<p>Exception raised when attempting to call a numpy function on a pandas object, but that function is not supported by the object e.g. <code>np.cumsum(groupby_object)</code>.</p> </dd>
</dl><div class="_attribution">
  <p class="_attribution-p">
    &copy; 2008&ndash;2012, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team<br>Licensed under the 3-clause BSD License.<br>
    <a href="https://pandas.pydata.org/pandas-docs/version/0.25.0/reference/api/pandas.errors.UnsupportedFunctionCall.html" class="_attribution-link">https://pandas.pydata.org/pandas-docs/version/0.25.0/reference/api/pandas.errors.UnsupportedFunctionCall.html</a>
  </p>
</div>
