<h1 class="fqn">Function std::intrinsics::try</h1>
<pre class="rust fn" data-language="rust">pub unsafe extern "rust-intrinsic" fn try(    try_fn: fn(*mut u8),     data: *mut u8,     catch_fn: fn(*mut u8, *mut u8)) -&gt; i32</pre>
<div class="item-info"><div class="stab unstable">
<span class="emoji">🔬</span> This is a nightly-only experimental API. (<code>core_intrinsics</code>)</div></div>
<p>Rust’s “try catch” construct which invokes the function pointer <code>try_fn</code> with the data pointer <code>data</code>.</p> <p>The third argument is a function called if a panic occurs. This function takes the data pointer and a pointer to the target-specific exception object that was caught. For more information see the compiler’s source as well as std’s catch implementation.</p><div class="_attribution">
  <p class="_attribution-p">
    <a href="https://doc.rust-lang.org/std/intrinsics/fn.try.html" class="_attribution-link" target="_blank">https://doc.rust-lang.org/std/intrinsics/fn.try.html</a>
  </p>
</div>
