    <h1 id="firstHeading" class="firstHeading">std::future_error</h1>            <table class="t-dcl-begin"> <tr class="t-dsc-header"> <th> Defined in header <code><a href="../header/future" title="cpp/header/future">&lt;future&gt;</a></code> </th> <th> </th> <th> </th> </tr> <tr class="t-dcl t-since-cxx11"> <td> <pre data-language="cpp">class future_error;</pre>
</td> <td class="t-dcl-nopad"> </td> <td> <span class="t-mark-rev t-since-cxx11">(since C++11)</span> </td> </tr>  </table> <p>The class <code>std::future_error</code> defines an exception object that is thrown on failure by the functions in the thread library that deal with asynchronous execution and shared states (<code><a href="future" title="cpp/thread/future">std::future</a></code>, <code><a href="promise" title="cpp/thread/promise">std::promise</a></code>, etc). Similar to <code><a href="../error/system_error" title="cpp/error/system error">std::system_error</a></code>, this exception carries an error code compatible with <code><a href="../error/error_code" title="cpp/error/error code">std::error_code</a></code>.</p>
<div class="t-inheritance-diagram"> <div class="center"><div class="noresize">
<map name="ImageMap_1_38229165"><area href="/w/cpp/error/exception" shape="rect" coords="5,4,107,36" alt="cpp/error/exception" title="cpp/error/exception">
<area href="/w/cpp/error/logic_error" shape="rect" coords="135,4,238,36" alt="cpp/error/logic error" title="cpp/error/logic error"></map><img alt="std-future error-inheritance.svg" src="" width="374" height="40" usemap="#ImageMap_1_38229165">
</div></div> <div style="text-align:center;"> <p>Inheritance diagram.</p>
</div> </div>  <h3 id="Member_functions"> Member functions</h3> <table class="t-dsc-begin"> <tr class="t-dsc"> <td> <div><a href="future_error/future_error" title="cpp/thread/future error/future error"> <span class="t-lines"><span>(constructor)</span></span></a></div> </td> <td> creates a <code>std::future_error</code> object <br> <span class="t-mark">(public member function)</span>  </td>
</tr> <tr class="t-dsc"> <td> <div><a href="future_error/operator=" title="cpp/thread/future error/operator="> <span class="t-lines"><span>operator=</span></span></a></div> </td> <td> replaces the <code>std::future_error</code> object <br> <span class="t-mark">(public member function)</span>  </td>
</tr> <tr class="t-dsc"> <td> <div><a href="future_error/code" title="cpp/thread/future error/code"> <span class="t-lines"><span>code</span></span></a></div> </td> <td> returns the error code <br> <span class="t-mark">(public member function)</span>  </td>
</tr> <tr class="t-dsc"> <td> <div><a href="future_error/what" title="cpp/thread/future error/what"> <span class="t-lines"><span>what</span></span></a></div> </td> <td> returns the explanatory string specific to the error code <br> <span class="t-mark">(public member function)</span>  </td>
</tr> </table> <div class="t-inherited"> <h2 id="Inherited_from_std::logic_error"> Inherited from <a href="../error/logic_error" title="cpp/error/logic error"> std::logic_error</a> </h2> </div> <div class="t-inherited"> <h2 id="Inherited_from_std::exception"> Inherited from <a href="../error/exception" title="cpp/error/exception"> std::exception</a> </h2> <h3 id="Member_functions_2"> Member functions</h3> <table class="t-dsc-begin"> <tr class="t-dsc"> <td> <div><a href="../error/exception/~exception" title="cpp/error/exception/~exception"> <span class="t-lines"><span>(destructor)</span></span></a></div>
<div><span class="t-lines"><span><span class="t-cmark">[virtual]</span></span></span></div> </td> <td> destroys the exception object <br> <span class="t-mark">(virtual public member function of <code>std::exception</code>)</span>  </td>
</tr> <tr class="t-dsc"> <td> <div><a href="../error/exception/what" title="cpp/error/exception/what"> <span class="t-lines"><span>what</span></span></a></div>
<div><span class="t-lines"><span><span class="t-cmark">[virtual]</span></span></span></div> </td> <td> returns an explanatory string <br> <span class="t-mark">(virtual public member function of <code>std::exception</code>)</span>  </td>
</tr> </table> </div> <h3 id="Example"> Example</h3> <div class="t-example"> <div class="cpp source-cpp"><pre data-language="cpp">#include &lt;future&gt;
#include &lt;iostream&gt;
 
int main()
{
    std::future&lt;int&gt; empty;
    try {
        int n = empty.get(); // The behavior is undefined, but
                             // some implementations throw std::future_error
    } catch (const std::future_error&amp; e) {
        std::cout &lt;&lt; "Caught a future_error with code \"" &lt;&lt; e.code()
                  &lt;&lt; "\"\nMessage: \"" &lt;&lt; e.what() &lt;&lt; "\"\n";
    }
}</pre></div> <p>Possible output:</p>
<div class="text source-text"><pre data-language="c">Caught a future_error with code "future:3"
Message: "No associated state"</pre></div> </div> <h3 id="See_also"> See also</h3> <table class="t-dsc-begin"> <tr class="t-dsc"> <td> <div><a href="future_errc" title="cpp/thread/future errc"> <span class="t-lines"><span>future_errc</span></span></a></div>
<div><span class="t-lines"><span><span class="t-mark-rev t-since-cxx11">(C++11)</span></span></span></div> </td> <td> identifies the future error codes <br> <span class="t-mark">(enum)</span>  </td>
</tr> </table>           <div class="_attribution">
  <p class="_attribution-p">
    &copy; cppreference.com<br>Licensed under the Creative Commons Attribution-ShareAlike Unported License v3.0.<br>
    <a href="https://en.cppreference.com/w/cpp/thread/future_error" class="_attribution-link">https://en.cppreference.com/w/cpp/thread/future_error</a>
  </p>
</div>
