    <h1 id="firstHeading" class="firstHeading">
<code>throw</code> expression</h1>            <p>Signals an erroneous condition and executes an error handler.</p>
<h3 id="Syntax"> Syntax</h3> <table class="t-sdsc-begin">  <tr class="t-sdsc"> <td> <code>throw</code> <span class="t-spar">expression</span> </td> <td> (1) </td> <td class="t-sdsc-nopad"> </td>
</tr>  <tr class="t-sdsc"> <td> <code>throw</code> </td> <td> (2) </td> <td class="t-sdsc-nopad"> </td>
</tr> 
</table> <h3 id="Explanation"> Explanation</h3> See <a href="try_catch" title="cpp/language/try catch">try-catch block</a> for more information about <i>try</i> and <i>catch</i> (exception handler) blocks  <span class="t-li">1)</span> First, <a href="copy_initialization" title="cpp/language/copy initialization">copy-initializes</a> the <i>exception object</i> from <span class="t-spar">expression</span> <table class="t-rev-begin"> <tr class="t-rev t-since-cxx11">
<td> <ul><li> This may call the move constructor for rvalue expression </li></ul> </td> <td><span class="t-mark-rev t-since-cxx11">(since C++11)</span></td>
</tr> </table> <table class="t-rev-begin"> <tr class="t-rev t-since-cxx17">
<td> <ul><li> This may also call the move constructor for lvalue expressions if they name local variables or function or catch-clause parameters whose scope does not extend past the innermost enclosing try-block (if any), by same two-step overload resolution as in <a href="return" title="cpp/language/return">return statement</a> </li></ul> </td> <td><span class="t-mark-rev t-since-cxx17">(since C++17)</span></td>
</tr> </table> <ul><li> The copy<span class="t-rev-inl t-since-cxx11"><span>/move</span> <span><span class="t-mark-rev t-since-cxx11">(since C++11)</span></span></span> may be subject to <a href="copy_elision" title="cpp/language/copy elision">copy elision</a> </li></ul> <table class="t-rev-begin"> <tr class="t-rev t-since-cxx14">
<td> <ul><li> Even if copy initialization selects the move constructor, copy initialization from lvalue must be well-formed, and the destructor must be accessible </li></ul> </td> <td><span class="t-mark-rev t-since-cxx14">(since C++14)</span></td>
</tr> </table>  then transfers control to the <a href="try_catch" title="cpp/language/try catch">exception handler</a> with the matching type for which the compound statement or member initializer list that follows the keyword <code>try</code> was most recently entered and not exited by this thread of execution.  <div class="t-li1">
<span class="t-li">2)</span> Rethrows the currently handled exception. Abandons the execution of the current catch block and passes control to the next matching exception handler (but not to another catch clause after the same try block: its compound-statement is considered to have been 'exited'), reusing the existing exception object: no new objects are made. This form is only allowed when an exception is presently being handled (it calls <code><a href="../error/terminate" title="cpp/error/terminate">std::terminate</a></code> if used otherwise). The catch clause associated with a <a href="function-try-block" title="cpp/language/function-try-block">function-try-block</a> must exit via rethrowing if used on a constructor.</div> <p>See <code><a href="../error/terminate" title="cpp/error/terminate">std::terminate</a></code><span class="t-rev-inl t-until-cxx17"><span> and <code><a href="../error/unexpected" title="cpp/error/unexpected">std::unexpected</a></code></span> <span><span class="t-mark-rev t-until-cxx17">(until C++17)</span></span></span> for the handling of errors that arise during exception handling.</p>
<h3 id="The_exception_object"> The exception object</h3> <p>The exception object is a temporary object in unspecified storage that is constructed by the <code>throw</code> expression.</p>
<p>The type of the <i>exception object</i> is the static type of <span class="t-spar">expression</span> with top-level <a href="cv" title="cpp/language/cv">cv-qualifiers</a> removed. Array and function types are adjusted to pointer and pointer to function types, respectively. If the type of the exception object would be an <a href="incomplete_type" title="cpp/language/incomplete type" class="mw-redirect">incomplete type</a>, an <a href="abstract_class" title="cpp/language/abstract class">abstract class</a> type, or pointer to incomplete type other than pointer to (cv-qualified) void, the throw-expression is a compile-time error. If the type of <span class="t-spar">expression</span> is a class type, its copy<span class="t-rev-inl t-since-cxx11"><span>/move</span> <span><span class="t-mark-rev t-since-cxx11">(since C++11)</span></span></span> constructor and destructor must be accessible even if <a href="copy_elision" title="cpp/language/copy elision">copy elision</a> takes place.</p>
<p>Unlike other temporary objects, the exception object is considered to be an lvalue argument when initializing the catch clause parameters, so it can be caught by lvalue reference, modified, and rethrown.</p>
<p>The exception object persists until the last catch clause exits other than by rethrowing (if not by rethrowing, it is destroyed immediately after the destruction of the catch clause's parameter), or until the last <code><a href="../error/exception_ptr" title="cpp/error/exception ptr">std::exception_ptr</a></code> that references this object is destroyed (in which case the exception object is destroyed just before the destructor of <code><a href="../error/exception_ptr" title="cpp/error/exception ptr">std::exception_ptr</a></code> returns.</p>
<h3 id="Stack_unwinding"> Stack unwinding</h3> <p>Once the exception object is constructed, the control flow works backwards (up the call stack) until it reaches the start of a <a href="try_catch" title="cpp/language/try catch">try block</a>, at which point the parameters of all associated <code>catch</code> blocks are compared, in order of appearance, with the type of the exception object to find a match (see <a href="try_catch" title="cpp/language/try catch">try-catch</a> for details on this process). If no match is found, the control flow continues to unwind the stack until the next <code>try</code> block, and so on. If a match is found, the control flow jumps to the matching <code>catch</code> block.</p>
<p>As the control flow moves up the call stack, destructors are invoked for all objects with <a href="storage_duration" title="cpp/language/storage duration">automatic storage duration</a> that are constructed, but not yet destroyed, since the corresponding try-block was entered, in reverse order of completion of their constructors. <span class="t-rev-inl t-since-cxx14"><span> If an exception is thrown from a destructor of a local variable or of a temporary used in a <a href="return" title="cpp/language/return">return</a> statement, the destructor for the object returned from the function is also invoked.</span> <span><span class="t-mark-rev t-since-cxx14">(since C++14)</span></span></span>.</p>
<p>If an exception is thrown from a constructor or (rare) from a destructor of an object (regardless of the object's storage duration), destructors are called for all fully-constructed non-static <span class="t-rev-inl t-until-cxx14"><span>non-variant </span> <span><span class="t-mark-rev t-until-cxx14">(until C++14)</span></span></span>members and base classes, in reverse order of completion of their constructors. <span class="t-rev-inl t-since-cxx14"><span> Variant members of union-like classes are only destroyed in the case of unwinding from constructor, and if the active member changed between initialization and destruction, the behavior is undefined.</span> <span><span class="t-mark-rev t-since-cxx14">(since C++14)</span></span></span>.</p>
<table class="t-rev-begin"> <tr class="t-rev t-since-cxx11">
<td> <p>If a delegating constructor exits with an exception after the non-delegating constructor successfully completed, the destructor for this object is called.</p>
</td> <td><span class="t-mark-rev t-since-cxx11">(since C++11)</span></td>
</tr> </table> <p>If the exception is thrown from a constructor that is invoked by a <a href="new" title="cpp/language/new">new-expression</a>, the matching <a href="../memory/new/operator_delete" title="cpp/memory/new/operator delete">deallocation function</a> is called, if available.</p>
<p>This process is called <i>stack unwinding</i>.</p>
<p>If any function that is called directly by the stack unwinding mechanism, after initialization of the exception object and before the start of the exception handler, exits with an exception, <code><a href="../error/terminate" title="cpp/error/terminate">std::terminate</a></code> is called. Such functions include <a href="destructor" title="cpp/language/destructor">destructors</a> of objects with automatic storage duration whose scopes are exited, and the copy constructor of the exception object that is called (if not <a href="copy_elision" title="cpp/language/copy elision">elided</a>) to initialize catch-by-value arguments.</p>
<p>If an exception is thrown and not caught, including exceptions that escape the initial function of <code><a href="../thread/thread" title="cpp/thread/thread">std::thread</a></code>, the main function, and the constructor or destructor of any static or thread-local objects, then <code><a href="../error/terminate" title="cpp/error/terminate">std::terminate</a></code> is called. It is implementation-defined whether any stack unwinding takes place for uncaught exceptions.</p>
<h3 id="Notes"> Notes</h3> <p>When rethrowing exceptions, the second form must be used to avoid object slicing in the (typical) case where exception objects use inheritance:</p>
<div class="cpp source-cpp"><pre data-language="cpp">try
{
    std::string("abc").substr(10); // throws std::length_error
}
catch (const std::exception&amp; e)
{
    std::cout &lt;&lt; e.what() &lt;&lt; '\n';
//  throw e; // copy-initializes a new exception object of type std::exception
    throw;   // rethrows the exception object of type std::length_error
}</pre></div> <p>The throw-expression is classified as <a href="value_category" title="cpp/language/value category">prvalue expression</a> of type <code>void</code>. Like any other expression, it may be a sub-expression in another expression, most commonly in the <a href="operator_other#Conditional_operator" title="cpp/language/operator other">conditional operator</a>:</p>
<div class="cpp source-cpp"><pre data-language="cpp">double f(double d)
{
    return d &gt; 1e7 ? throw std::overflow_error("too big") : d;
}
 
int main()  
{
    try
    {
        std::cout &lt;&lt; f(1e10) &lt;&lt; '\n';
    }
    catch (const std::overflow_error&amp; e)
    {
        std::cout &lt;&lt; e.what() &lt;&lt; '\n';
    }
}</pre></div> <h3 id="Keywords"> Keywords</h3> <p><a href="../keyword/throw" title="cpp/keyword/throw"><code>throw</code></a>.</p>
<h3 id="Example"> Example</h3> <div class="t-example"> <div class="cpp source-cpp"><pre data-language="cpp">#include &lt;iostream&gt;
#include &lt;stdexcept&gt;
 
struct A
{
    int n;
 
    A(int n = 0): n(n) { std::cout &lt;&lt; "A(" &lt;&lt; n &lt;&lt; ") constructed successfully\n"; }
    ~A() { std::cout &lt;&lt; "A(" &lt;&lt; n &lt;&lt; ") destroyed\n"; }
};
 
int foo()
{
    throw std::runtime_error("error");
}
 
struct B
{
    A a1, a2, a3;
 
    B() try : a1(1), a2(foo()), a3(3)
    {
        std::cout &lt;&lt; "B constructed successfully\n";
    }
    catch(...)
    {
            std::cout &lt;&lt; "B::B() exiting with exception\n";
    }
 
    ~B() { std::cout &lt;&lt; "B destroyed\n"; }
};
 
struct C : A, B
{
    C() try
    {
        std::cout &lt;&lt; "C::C() completed successfully\n";
    }
    catch(...)
    {
        std::cout &lt;&lt; "C::C() exiting with exception\n";
    }
 
    ~C() { std::cout &lt;&lt; "C destroyed\n"; }
};
 
int main () try
{
    // creates the A base subobject
    // creates the a1 member of B
    // fails to create the a2 member of B
    // unwinding destroys the a1 member of B
    // unwinding destroys the A base subobject
    C c;
}
catch (const std::exception&amp; e)
{
    std::cout &lt;&lt; "main() failed to create C with: " &lt;&lt; e.what();
}</pre></div> <p>Output:</p>
<div class="text source-text"><pre data-language="c">A(0) constructed successfully
A(1) constructed successfully
A(1) destroyed
B::B() exiting with exception
A(0) destroyed
C::C() exiting with exception
main() failed to create C with: error</pre></div> </div> <h3 id="Defect_reports"> Defect reports</h3> <p>The following behavior-changing defect reports were applied retroactively to previously published C++ standards.</p>
<table class="dsctable"> <tr> <th> DR </th> <th> Applied to </th> <th> Behavior as published </th> <th> Correct behavior </th>
</tr> <tr> <td> <a rel="nofollow" class="external text" href="https://cplusplus.github.io/CWG/issues/499.html">CWG 499</a> </td> <td> C++98 </td> <td> an array with unknown bound could not be thrown becuase<br>its type is incomplete, but an exception object can be<br>created from the decayed pointer without any problem </td> <td> apply the type completion<br>requirement to the<br>exception object instead </td>
</tr> <tr> <td> <a rel="nofollow" class="external text" href="https://cplusplus.github.io/CWG/issues/668.html">CWG 668</a> </td> <td> C++98 </td> <td> <code><a href="../error/terminate" title="cpp/error/terminate">std::terminate</a></code> was not called if an exception is thrown<br>from the destructor of a local non-automatic object </td> <td> call <code><a href="../error/terminate" title="cpp/error/terminate">std::terminate</a></code><br>in this case </td>
</tr> <tr> <td> <a rel="nofollow" class="external text" href="https://cplusplus.github.io/CWG/issues/1863.html">CWG 1863</a> </td> <td> C++14 </td> <td> copy constructor was not required for move-only<br>exception objects when thrown, but copying allowed later </td> <td> copy constructor required </td>
</tr> <tr> <td> <a rel="nofollow" class="external text" href="https://cplusplus.github.io/CWG/issues/1866.html">CWG 1866</a> </td> <td> C++14 </td> <td> variant members were leaked on stack unwinding from constructor </td> <td> variant members destroyed </td>
</tr> <tr> <td> <a rel="nofollow" class="external text" href="https://cplusplus.github.io/CWG/issues/2176.html">CWG 2176</a> </td> <td> C++14 </td> <td> throw from a local variable destructor<br>could skip return value destructor </td> <td> function return value<br>added to unwinding </td>
</tr>
</table> <h3 id="See_also"> See also</h3> <ul>
<li> <a href="copy_elision" title="cpp/language/copy elision">copy elision</a> </li>
<li> <a href="try_catch" title="cpp/language/try catch">try-catch block</a> </li>
<li> <a href="noexcept_spec" title="cpp/language/noexcept spec"><code>noexcept</code> specifier</a> </li>
<li> <a href="except_spec" title="cpp/language/except spec">dynamic exception specifications</a> </li>
</ul>           <div class="_attribution">
  <p class="_attribution-p">
    &copy; cppreference.com<br>Licensed under the Creative Commons Attribution-ShareAlike Unported License v3.0.<br>
    <a href="https://en.cppreference.com/w/cpp/language/throw" class="_attribution-link">https://en.cppreference.com/w/cpp/language/throw</a>
  </p>
</div>
