   <h1 id="firstHeading" class="firstHeading">std::current_exception</h1>            <table class="t-dcl-begin"> <tr class="t-dsc-header"> <th> Defined in header <code><a href="../header/exception" title="cpp/header/exception">&lt;exception&gt;</a></code> </th> <th> </th> <th> </th> </tr> <tr class="t-dcl t-since-cxx11"> <td> <pre data-language="cpp">std::exception_ptr current_exception() noexcept;</pre>
</td> <td class="t-dcl-nopad"> </td> <td> <span class="t-mark-rev t-since-cxx11">(since C++11)</span> </td> </tr>  </table> <p>If called during exception handling (typically, in a <code>catch</code> clause), captures the current exception object and creates an <code><a href="exception_ptr" title="cpp/error/exception ptr">std::exception_ptr</a></code> that holds either a copy or a reference to that exception object (depending on the implementation). The referenced object remains valid at least as long as there is an <code>exception_ptr</code> object that refers to it.</p>
<p>If the implementation of this function requires a call to <code>new</code> and the call fails, the returned pointer will hold a reference to an instance of <code><a href="../memory/new/bad_alloc" title="cpp/memory/new/bad alloc">std::bad_alloc</a></code>.</p>
<p>If the implementation of this function requires copying the captured exception object and its copy constructor throws an exception, the returned pointer will hold a reference to the exception thrown. If the copy constructor of the thrown exception object also throws, the returned pointer may hold a reference to an instance of <code><a href="bad_exception" title="cpp/error/bad exception">std::bad_exception</a></code> to break the endless loop.</p>
<p>If the function is called when no exception is being handled, an empty <code><a href="exception_ptr" title="cpp/error/exception ptr">std::exception_ptr</a></code> is returned.</p>
<h3 id="Parameters">Parameters</h3> <p>(none).</p>
<h3 id="Return_value">Return value</h3> <p>An instance of <code><a href="exception_ptr" title="cpp/error/exception ptr">std::exception_ptr</a></code> holding a reference to the exception object, or a copy of the exception object, or to an instance of <code><a href="../memory/new/bad_alloc" title="cpp/memory/new/bad alloc">std::bad_alloc</a></code> or to an instance of <code><a href="bad_exception" title="cpp/error/bad exception">std::bad_exception</a></code>.</p>
<h3 id="Example">Example</h3> 
<div class="t-example"> <div class="cpp source-cpp"><pre data-language="cpp">#include &lt;iostream&gt;
#include &lt;string&gt;
#include &lt;exception&gt;
#include &lt;stdexcept&gt;
 
void handle_eptr(std::exception_ptr eptr) // passing by value is ok
{
    try {
        if (eptr) {
            std::rethrow_exception(eptr);
        }
    } catch(const std::exception&amp; e) {
        std::cout &lt;&lt; "Caught exception \"" &lt;&lt; e.what() &lt;&lt; "\"\n";
    }
}
 
int main()
{
    std::exception_ptr eptr;
    try {
        std::string().at(1); // this generates an std::out_of_range
    } catch(...) {
        eptr = std::current_exception(); // capture
    }
    handle_eptr(eptr);
} // destructor for std::out_of_range called here, when the eptr is destructed</pre></div> <p>Output:</p>
<div class="text source-text"><pre data-language="c">Caught exception "basic_string::at"</pre></div> </div> <h3 id="See_also">See also</h3> <table class="t-dsc-begin"> <tr class="t-dsc"> <td> <div><a href="exception_ptr" title="cpp/error/exception ptr"> <span class="t-lines"><span>exception_ptr</span></span></a></div>
<div><span class="t-lines"><span><span class="t-mark-rev t-since-cxx11">(C++11)</span></span></span></div> </td> <td> shared pointer type for handling exception objects <br> <span class="t-mark">(typedef)</span> </td>
</tr> <tr class="t-dsc"> <td> <div><a href="rethrow_exception" title="cpp/error/rethrow exception"> <span class="t-lines"><span>rethrow_exception</span></span></a></div>
<div><span class="t-lines"><span><span class="t-mark-rev t-since-cxx11">(C++11)</span></span></span></div> </td> <td> throws the exception from an <code><a href="exception_ptr" title="cpp/error/exception ptr">std::exception_ptr</a></code> <br> <span class="t-mark">(function)</span> </td>
</tr> <tr class="t-dsc"> <td> <div><a href="make_exception_ptr" title="cpp/error/make exception ptr"> <span class="t-lines"><span>make_exception_ptr</span></span></a></div>
<div><span class="t-lines"><span><span class="t-mark-rev t-since-cxx11">(C++11)</span></span></span></div> </td> <td> creates an <code><a href="exception_ptr" title="cpp/error/exception ptr">std::exception_ptr</a></code> from an exception object <br> <span class="t-mark">(function template)</span> </td>
</tr> </table>          <div class="_attribution">
  <p class="_attribution-p">
    &copy; cppreference.com<br>Licensed under the Creative Commons Attribution-ShareAlike Unported License v3.0.<br>
    <a href="http://en.cppreference.com/w/cpp/error/current_exception" class="_attribution-link">http://en.cppreference.com/w/cpp/error/current_exception</a>
  </p>
</div>
