    <h1 id="firstHeading" class="firstHeading">std::uncaught_exception, std::uncaught_exceptions</h1>            <table class="t-dcl-begin"> <tr class="t-dsc-header"> <th> Defined in header <code><a href="../header/exception" title="cpp/header/exception">&lt;exception&gt;</a></code> </th> <th> </th> <th> </th> </tr>  <tr class="t-dcl-rev-aux"> <td></td> <td rowspan="3">(1)</td> <td></td> </tr> <tr class="t-dcl t-until-cxx11"> <td> <pre data-language="cpp">bool uncaught_exception() throw();</pre>
</td>  <td> <span class="t-mark-rev t-until-cxx11">(until C++11)</span> </td> </tr> <tr class="t-dcl t-since-cxx11 t-until-cxx20"> <td> <pre data-language="cpp">bool uncaught_exception() noexcept;</pre>
</td>  <td> <span class="t-mark-rev t-since-cxx11">(since C++11)</span> <br><span class="t-mark">(deprecated in C++17)</span> <br><span class="t-mark-rev t-until-cxx20">(removed in C++20)</span> </td> </tr>  <tr class="t-dcl t-since-cxx17"> <td> <pre data-language="cpp">int uncaught_exceptions() noexcept;</pre>
</td> <td> (2) </td> <td> <span class="t-mark-rev t-since-cxx17">(since C++17)</span> </td> </tr>  </table> <div class="t-li1">
<span class="t-li">1)</span> Detects if the current thread has a live exception object, that is, an exception has been thrown or rethrown and not yet entered a matching catch clause, <code><a href="terminate" title="cpp/error/terminate">std::terminate</a></code> or <code><a href="unexpected" title="cpp/error/unexpected">std::unexpected</a></code>. In other words, <code>std::uncaught_exception</code> detects if <a href="../language/throw#Stack_unwinding" title="cpp/language/throw">stack unwinding</a> is currently in progress.</div> <div class="t-li1">
<span class="t-li">2)</span> Detects how many exceptions in the current thread have been thrown or rethrown and not yet entered their matching catch clauses. </div> <p>Sometimes it's safe to throw an exception even while <code>std::uncaught_exception() == true</code>. For example, if <a href="../language/throw#Stack_unwinding" title="cpp/language/throw">stack unwinding</a> causes an object to be destructed, the destructor for that object could run code that throws an exception as long as the exception is caught by some catch block before escaping the destructor.</p>
<h3 id="Parameters"> Parameters</h3> <p>(none).</p>
<h3 id="Return_value"> Return value</h3> <div class="t-li1">
<span class="t-li">1)</span> <code>true</code> if stack unwinding is currently in progress in this thread.</div> <div class="t-li1">
<span class="t-li">2)</span> The number of uncaught exception objects in the current thread.</div> <h3 id="Notes"> Notes</h3> <p>An example where int-returning <code>uncaught_exceptions</code> is used is the <a rel="nofollow" class="external text" href="http://www.boost.org/doc/libs/release/libs/log/doc/html/index.html">boost.log</a> library: the expression <code>BOOST_LOG(logger) &lt;&lt; foo();</code> first creates a guard object and records the number of uncaught exceptions in its constructor. The output is performed by the guard object's destructor unless foo() throws (in which case the number of uncaught exceptions in the destructor is greater than what the constructor observed).</p>
<p><a href="../feature_test#Library_features" title="cpp/feature test">Feature testing</a> macro: <a href="../utility/feature_test" title="cpp/utility/feature test"><code>__cpp_lib_uncaught_exceptions</code></a>.</p>
<h3 id="Example"> Example</h3> <div class="t-example"> <div class="cpp source-cpp"><pre data-language="cpp">#include &lt;iostream&gt;
#include &lt;exception&gt;
#include &lt;stdexcept&gt;
 
struct Foo {
    int count = std::uncaught_exceptions();
    ~Foo() {
        std::cout &lt;&lt; (count == std::uncaught_exceptions()
            ? "~Foo() called normally\n"
            : "~Foo() called during stack unwinding\n");
    }
};
int main()
{
    Foo f;
    try {
        Foo f;
        std::cout &lt;&lt; "Exception thrown\n";
        throw std::runtime_error("test exception");
    } catch (const std::exception&amp; e) {
        std::cout &lt;&lt; "Exception caught: " &lt;&lt; e.what() &lt;&lt; '\n';
    }
}</pre></div> <p>Output:</p>
<div class="text source-text"><pre data-language="c">Exception thrown
~Foo() called during stack unwinding
Exception caught: test exception
~Foo() called normally</pre></div> </div> <h3 id="See_also"> See also</h3> <table class="t-dsc-begin"> <tr class="t-dsc"> <td> <div><a href="terminate" title="cpp/error/terminate"> <span class="t-lines"><span>terminate</span></span></a></div> </td> <td> function called when exception handling fails <br> <span class="t-mark">(function)</span>  </td>
</tr> <tr class="t-dsc"> <td> <div><a href="exception_ptr" title="cpp/error/exception ptr"> <span class="t-lines"><span>exception_ptr</span></span></a></div>
<div><span class="t-lines"><span><span class="t-mark-rev t-since-cxx11">(C++11)</span></span></span></div> </td> <td> shared pointer type for handling exception objects <br> <span class="t-mark">(typedef)</span>  </td>
</tr> <tr class="t-dsc"> <td> <div><a href="current_exception" title="cpp/error/current exception"> <span class="t-lines"><span>current_exception</span></span></a></div>
<div><span class="t-lines"><span><span class="t-mark-rev t-since-cxx11">(C++11)</span></span></span></div> </td> <td> captures the current exception in a <code><a href="exception_ptr" title="cpp/error/exception ptr">std::exception_ptr</a></code> <br> <span class="t-mark">(function)</span>  </td>
</tr> </table> <h3 id="External_links"> External links</h3> <ul>
<li> <a rel="nofollow" class="external text" href="http://www.gotw.ca/gotw/047.htm">GOTW issue 47: Uncaught Exceptions</a> </li>
<li> <a rel="nofollow" class="external text" href="http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4152.pdf">Rationale for <code>std::uncaught_exceptions</code></a> </li>
</ul>           <div class="_attribution">
  <p class="_attribution-p">
    &copy; cppreference.com<br>Licensed under the Creative Commons Attribution-ShareAlike Unported License v3.0.<br>
    <a href="https://en.cppreference.com/w/cpp/error/uncaught_exception" class="_attribution-link">https://en.cppreference.com/w/cpp/error/uncaught_exception</a>
  </p>
</div>
