<h1 id="urllib-error-exception-classes-raised-by-urllib-request">urllib.error â€” Exception classes raised by urllib.request</h1> <p id="module-urllib.error"><strong>Source code:</strong> <a class="reference external" href="https://github.com/python/cpython/tree/3.9/Lib/urllib/error.py">Lib/urllib/error.py</a></p>  <p>The <a class="reference internal" href="#module-urllib.error" title="urllib.error: Exception classes raised by urllib.request."><code>urllib.error</code></a> module defines the exception classes for exceptions raised by <a class="reference internal" href="urllib.request#module-urllib.request" title="urllib.request: Extensible library for opening URLs."><code>urllib.request</code></a>. The base exception class is <a class="reference internal" href="#urllib.error.URLError" title="urllib.error.URLError"><code>URLError</code></a>.</p> <p>The following exceptions are raised by <a class="reference internal" href="#module-urllib.error" title="urllib.error: Exception classes raised by urllib.request."><code>urllib.error</code></a> as appropriate:</p> <dl class="exception"> <dt id="urllib.error.URLError">
<code>exception urllib.error.URLError</code> </dt> <dd>
<p>The handlers raise this exception (or derived exceptions) when they run into a problem. It is a subclass of <a class="reference internal" href="exceptions#OSError" title="OSError"><code>OSError</code></a>.</p> <dl class="attribute"> <dt id="urllib.error.URLError.reason">
<code>reason</code> </dt> <dd>
<p>The reason for this error. It can be a message string or another exception instance.</p> </dd>
</dl> <div class="versionchanged"> <p><span class="versionmodified changed">Changed in version 3.3: </span><a class="reference internal" href="#urllib.error.URLError" title="urllib.error.URLError"><code>URLError</code></a> has been made a subclass of <a class="reference internal" href="exceptions#OSError" title="OSError"><code>OSError</code></a> instead of <a class="reference internal" href="exceptions#IOError" title="IOError"><code>IOError</code></a>.</p> </div> </dd>
</dl> <dl class="exception"> <dt id="urllib.error.HTTPError">
<code>exception urllib.error.HTTPError</code> </dt> <dd>
<p>Though being an exception (a subclass of <a class="reference internal" href="#urllib.error.URLError" title="urllib.error.URLError"><code>URLError</code></a>), an <a class="reference internal" href="#urllib.error.HTTPError" title="urllib.error.HTTPError"><code>HTTPError</code></a> can also function as a non-exceptional file-like return value (the same thing that <a class="reference internal" href="urllib.request#urllib.request.urlopen" title="urllib.request.urlopen"><code>urlopen()</code></a> returns). This is useful when handling exotic HTTP errors, such as requests for authentication.</p> <dl class="attribute"> <dt id="urllib.error.HTTPError.code">
<code>code</code> </dt> <dd>
<p>An HTTP status code as defined in <a class="rfc reference external" href="https://tools.ietf.org/html/rfc2616.html" id="index-0"><strong>RFC 2616</strong></a>. This numeric value corresponds to a value found in the dictionary of codes as found in <a class="reference internal" href="http.server#http.server.BaseHTTPRequestHandler.responses" title="http.server.BaseHTTPRequestHandler.responses"><code>http.server.BaseHTTPRequestHandler.responses</code></a>.</p> </dd>
</dl> <dl class="attribute"> <dt id="urllib.error.HTTPError.reason">
<code>reason</code> </dt> <dd>
<p>This is usually a string explaining the reason for this error.</p> </dd>
</dl> <dl class="attribute"> <dt id="urllib.error.HTTPError.headers">
<code>headers</code> </dt> <dd>
<p>The HTTP response headers for the HTTP request that caused the <a class="reference internal" href="#urllib.error.HTTPError" title="urllib.error.HTTPError"><code>HTTPError</code></a>.</p> <div class="versionadded"> <p><span class="versionmodified added">New in version 3.4.</span></p> </div> </dd>
</dl> </dd>
</dl> <dl class="exception"> <dt id="urllib.error.ContentTooShortError">
<code>exception urllib.error.ContentTooShortError(msg, content)</code> </dt> <dd>
<p>This exception is raised when the <a class="reference internal" href="urllib.request#urllib.request.urlretrieve" title="urllib.request.urlretrieve"><code>urlretrieve()</code></a> function detects that the amount of the downloaded data is less than the expected amount (given by the <em>Content-Length</em> header). The <code>content</code> attribute stores the downloaded (and supposedly truncated) data.</p> </dd>
</dl><div class="_attribution">
  <p class="_attribution-p">
    &copy; 2001&ndash;2021 Python Software Foundation<br>Licensed under the PSF License.<br>
    <a href="https://docs.python.org/3.9/library/urllib.error.html" class="_attribution-link">https://docs.python.org/3.9/library/urllib.error.html</a>
  </p>
</div>
